CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE continents
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    code VARCHAR(10),
    CONSTRAINT pk_continents PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    continent_id BIGINT,
    name         VARCHAR(100)                            NOT NULL,
    iso_code     VARCHAR(10),
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE TABLE journals
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    short_summary     OID,
    trip_location_id  BIGINT,
    start_date        date,
    end_date          date,
    cover_photo_url   VARCHAR(500),
    reminders_enabled BOOLEAN,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_journals PRIMARY KEY (id)
);

CREATE TABLE location
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude          DOUBLE PRECISION,
    longitude         DOUBLE PRECISION,
    formatted_address VARCHAR(500),
    city              VARCHAR(100),
    state             VARCHAR(100),
    google_place_id   VARCHAR(255),
    country_id        BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE moment_media
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    moment_id  BIGINT                                  NOT NULL,
    media_url  VARCHAR(500)                            NOT NULL,
    media_type VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_moment_media PRIMARY KEY (id)
);

CREATE TABLE moments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    journal_id  BIGINT                                  NOT NULL,
    location_id BIGINT,
    name        VARCHAR(100)                            NOT NULL,
    description OID,
    date_time   TIMESTAMP WITHOUT TIME ZONE,
    category_id BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_moments PRIMARY KEY (id)
);

CREATE TABLE otp_codes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    code       VARCHAR(10)                             NOT NULL,
    type       VARCHAR(50)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    used_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_otp_codes PRIMARY KEY (id)
);

CREATE TABLE user_profiles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    profile_photo_url VARCHAR(500),
    cover_photo_url   VARCHAR(500),
    bio               OID,
    location_id       BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id)
);

CREATE TABLE user_social_accounts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    provider    VARCHAR(50)                             NOT NULL,
    provider_id VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_social_accounts PRIMARY KEY (id)
);

CREATE TABLE user_visited_countries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    country_id BIGINT                                  NOT NULL,
    visited_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_visited_countries PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    email       VARCHAR(100)                            NOT NULL,
    password    VARCHAR(255),
    is_verified BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE continents
    ADD CONSTRAINT uc_continents_code UNIQUE (code);

ALTER TABLE user_profiles
    ADD CONSTRAINT uc_user_profiles_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE countries
    ADD CONSTRAINT FK_COUNTRIES_ON_CONTINENT FOREIGN KEY (continent_id) REFERENCES continents (id);

ALTER TABLE journals
    ADD CONSTRAINT FK_JOURNALS_ON_TRIP_LOCATION FOREIGN KEY (trip_location_id) REFERENCES location (id);

ALTER TABLE journals
    ADD CONSTRAINT FK_JOURNALS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE location
    ADD CONSTRAINT FK_LOCATION_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE moments
    ADD CONSTRAINT FK_MOMENTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE moments
    ADD CONSTRAINT FK_MOMENTS_ON_JOURNAL FOREIGN KEY (journal_id) REFERENCES journals (id);

ALTER TABLE moments
    ADD CONSTRAINT FK_MOMENTS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES location (id);

ALTER TABLE moment_media
    ADD CONSTRAINT FK_MOMENT_MEDIA_ON_MOMENT FOREIGN KEY (moment_id) REFERENCES moments (id);

ALTER TABLE otp_codes
    ADD CONSTRAINT FK_OTP_CODES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_LOCATION FOREIGN KEY (location_id) REFERENCES location (id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_social_accounts
    ADD CONSTRAINT FK_USER_SOCIAL_ACCOUNTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_visited_countries
    ADD CONSTRAINT FK_USER_VISITED_COUNTRIES_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE user_visited_countries
    ADD CONSTRAINT FK_USER_VISITED_COUNTRIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);