INSERT INTO continents (name, code) VALUES ('Africa', 'AF');
INSERT INTO continents (name, code) VALUES ('Antarctica', 'AN');
INSERT INTO continents (name, code) VALUES ('Asia', 'AS');
INSERT INTO continents (name, code) VALUES ('Australia', 'AU');
INSERT INTO continents (name, code) VALUES ('Europe', 'EU');
INSERT INTO continents (name, code) VALUES ('North America', 'NA');
INSERT INTO continents (name, code) VALUES ('South America', 'SA');


INSERT INTO countries (name, iso_code, continent_id) VALUES
 ('Afghanistan', 'AF', (SELECT id FROM continents WHERE code = 'AS')),
 ('Albania', 'AL',  (SELECT id FROM continents WHERE code = 'EU')),
 ('Algeria', 'DZ',   (SELECT id FROM continents WHERE code = 'AF')),
 ('American Samoa', 'AS',   (SELECT id FROM continents WHERE code = 'AU')),
 ('Andorra', 'AD',  (SELECT id FROM continents WHERE code = 'EU')),
 ('Angola', 'AO',   (SELECT id FROM continents WHERE code = 'AF')),
 ('Anguilla', 'AI',   (SELECT id FROM continents WHERE code = 'NA')),
 ('Antigua and Barbuda', 'AG',  (SELECT id FROM continents WHERE code = 'NA')),
 ('Argentina', 'AR',   (SELECT id FROM continents WHERE code = 'SA')),
 ('Armenia', 'AM',   (SELECT id FROM continents WHERE code = 'AS')),
 ('Aruba', 'AW',   (SELECT id FROM continents WHERE code = 'NA')),
 ('Australia', 'AU',   (SELECT id FROM continents WHERE code = 'AU')),
 ('Austria', 'AT',   (SELECT id FROM continents WHERE code = 'EU')),
 ('Azerbaijan', 'AZ',   (SELECT id FROM continents WHERE code = 'AS')),
 ('Bahamas, The', 'BS',   (SELECT id FROM continents WHERE code = 'NA')),
 ('Bahrain', 'BH',  (SELECT id FROM continents WHERE code = 'AS')),
 ('Bangladesh', 'BD',   (SELECT id FROM continents WHERE code = 'AS')),
 ('Barbados', 'BB',   (SELECT id FROM continents WHERE code = 'NA')),
 ('Belarus', 'BY',   (SELECT id FROM continents WHERE code = 'EU')),
 ('Belgium', 'BE',  (SELECT id FROM continents WHERE code = 'EU')),
 ('Belize', 'BZ',   (SELECT id FROM continents WHERE code = 'NA')),
 ('Benin', 'BJ',   (SELECT id FROM continents WHERE code = 'AF')),
 ('Bermuda', 'BM',   (SELECT id FROM continents WHERE code = 'NA')),
 ('Bhutan', 'BT',   (SELECT id FROM continents WHERE code = 'AS')),
 ('Bolivia', 'BO',   (SELECT id FROM continents WHERE code = 'SA')),
 ('Bosnia and Herzegovina', 'BA', (SELECT id FROM continents WHERE code = 'EU')),
 ('Botswana', 'BW', (SELECT id FROM continents WHERE code = 'AF')),
 ('Brazil', 'BR', (SELECT id FROM continents WHERE code = 'SA')),
 ('British Virgin Islands', 'VG', (SELECT id FROM continents WHERE code = 'NA')),
 ('Brunei', 'BN', (SELECT id FROM continents WHERE code = 'AS')),
 ('Bulgaria', 'BG', (SELECT id FROM continents WHERE code = 'EU')),
 ('Burkina Faso', 'BF', (SELECT id FROM continents WHERE code = 'AF')),
 ('Burundi', 'BI', (SELECT id FROM continents WHERE code = 'AF')),
 ('Cambodia', 'KH', (SELECT id FROM continents WHERE code = 'AS')),
 ('Cameroon', 'CM', (SELECT id FROM continents WHERE code = 'AF')),
 ('Canada', 'CA', (SELECT id FROM continents WHERE code = 'NA')),
 ('Cape Verde', 'CV', (SELECT id FROM continents WHERE code = 'AF')),
 ('Cayman Islands', 'KY', (SELECT id FROM continents WHERE code = 'NA')),
 ('Central African Republic', 'CF', (SELECT id FROM continents WHERE code = 'AF')),
 ('Chad', 'TD', (SELECT id FROM continents WHERE code = 'AF')),
 ('Chile', 'CL', (SELECT id FROM continents WHERE code = 'SA')),
 ('China', 'CN', (SELECT id FROM continents WHERE code = 'AS')),
 ('Christmas Island', 'CX', (SELECT id FROM continents WHERE code = 'AS')),
 ('Cocos (Keeling) Islands', 'CC', (SELECT id FROM continents WHERE code = 'AS')),
 ('Colombia', 'CO', (SELECT id FROM continents WHERE code = 'SA')),
 ('Comoros', 'KM', (SELECT id FROM continents WHERE code = 'AF')),
 ('Congo, Republic of the', 'CG', (SELECT id FROM continents WHERE code = 'AF')),
 ('Cook Islands', 'CK', (SELECT id FROM continents WHERE code = 'AU')),
 ('Costa Rica', 'CR', (SELECT id FROM continents WHERE code = 'NA')),
 ('Cote d''Ivoire', 'CI', (SELECT id FROM continents WHERE code = 'AF')),
 ('Croatia', 'HR', (SELECT id FROM continents WHERE code = 'EU')),
 ('Cuba', 'CU', (SELECT id FROM continents WHERE code = 'NA')),
 ('Cyprus', 'CY', (SELECT id FROM continents WHERE code = 'AS')),
 ('Czech Republic', 'CZ', (SELECT id FROM continents WHERE code = 'EU')),
 ('Denmark', 'DK', (SELECT id FROM continents WHERE code = 'EU')),
 ('Djibouti', 'DJ', (SELECT id FROM continents WHERE code = 'AF')),
 ('Dominica', 'DM', (SELECT id FROM continents WHERE code = 'NA')),
 ('Dominican Republic', 'DO', (SELECT id FROM continents WHERE code = 'NA')),
 ('Ecuador', 'EC', (SELECT id FROM continents WHERE code = 'SA')),
 ('Egypt', 'EG', (SELECT id FROM continents WHERE code = 'AF')),
 ('El Salvador', 'SV', (SELECT id FROM continents WHERE code = 'NA')),
 ('Equatorial Guinea', 'GQ', (SELECT id FROM continents WHERE code = 'AF')),
 ('Eritrea', 'ER', (SELECT id FROM continents WHERE code = 'AF')),
 ('Estonia', 'EE', (SELECT id FROM continents WHERE code = 'EU')),
 ('Ethiopia', 'ET', (SELECT id FROM continents WHERE code = 'AF')),
 ('Falkland Islands (Islas Malvinas)', 'FK', (SELECT id FROM continents WHERE code = 'SA')),
 ('Faroe Islands', 'FO', (SELECT id FROM continents WHERE code = 'EU')),
 ('Fiji', 'FJ', (SELECT id FROM continents WHERE code = 'AU')),
 ('Finland', 'FI', (SELECT id FROM continents WHERE code = 'EU')),
 ('France', 'FR', (SELECT id FROM continents WHERE code = 'EU')),
 ('French Guiana', 'GF', (SELECT id FROM continents WHERE code = 'SA')),
 ('French Polynesia', 'PF', (SELECT id FROM continents WHERE code = 'AU')),
 ('Gabon', 'GA', (SELECT id FROM continents WHERE code = 'AF')),
 ('Gambia, The', 'GM', (SELECT id FROM continents WHERE code = 'AF')),
 ('Georgia', 'GE', (SELECT id FROM continents WHERE code = 'AS')),
 ('Germany', 'DE', (SELECT id FROM continents WHERE code = 'EU')),
 ('Ghana', 'GH', (SELECT id FROM continents WHERE code = 'AF')),
 ('Gibraltar', 'GI', (SELECT id FROM continents WHERE code = 'EU')),
 ('Greece', 'GR', (SELECT id FROM continents WHERE code = 'EU')),
 ('Greenland', 'GL', (SELECT id FROM continents WHERE code = 'NA')),
 ('Grenada', 'GD', (SELECT id FROM continents WHERE code = 'NA')),
 ('Guadeloupe', 'GP', (SELECT id FROM continents WHERE code = 'NA')),
 ('Guam', 'GU', (SELECT id FROM continents WHERE code = 'AU')),
 ('Guatemala', 'GT', (SELECT id FROM continents WHERE code = 'NA')),
 ('Guernsey', 'GG', (SELECT id FROM continents WHERE code = 'EU')),
 ('Guinea', 'GN', (SELECT id FROM continents WHERE code = 'AF')),
 ('Guinea-Bissau', 'GW', (SELECT id FROM continents WHERE code = 'AF')),
 ('Guyana', 'GY', (SELECT id FROM continents WHERE code = 'SA')),
 ('Haiti', 'HT', (SELECT id FROM continents WHERE code = 'NA')),
 ('Holy See (Vatican City)', 'VA', (SELECT id FROM continents WHERE code = 'EU')),
 ('Honduras', 'HN', (SELECT id FROM continents WHERE code = 'NA')),
 ('Hungary', 'HU', (SELECT id FROM continents WHERE code = 'EU')),
 ('Iceland', 'IS', (SELECT id FROM continents WHERE code = 'EU')),
 ('India', 'IN', (SELECT id FROM continents WHERE code = 'AS')),
 ('Indonesia', 'ID', (SELECT id FROM continents WHERE code = 'AS')),
 ('Iran', 'IR', (SELECT id FROM continents WHERE code = 'AS')),
 ('Iraq', 'IQ', (SELECT id FROM continents WHERE code = 'AS')),
 ('Ireland', 'IE', (SELECT id FROM continents WHERE code = 'EU')),
 ('Israel', 'IL', (SELECT id FROM continents WHERE code = 'AS')),
 ('Italy', 'IT', (SELECT id FROM continents WHERE code = 'EU')),
 ('Jamaica', 'JM', (SELECT id FROM continents WHERE code = 'NA')),
 ('Japan', 'JP', (SELECT id FROM continents WHERE code = 'AS')),
 ('Jersey', 'JE', (SELECT id FROM continents WHERE code = 'EU')),
 ('Jordan', 'JO', (SELECT id FROM continents WHERE code = 'AS')),
 ('Kazakhstan', 'KZ', (SELECT id FROM continents WHERE code = 'AS')),
 ('Kenya', 'KE', (SELECT id FROM continents WHERE code = 'AF')),
 ('Kiribati', 'KI', (SELECT id FROM continents WHERE code = 'AU')),
 ('Korea, North', 'KP', (SELECT id FROM continents WHERE code = 'AS')),
 ('Korea, South', 'KR', (SELECT id FROM continents WHERE code = 'AS')),
 ('Kuwait', 'KW', (SELECT id FROM continents WHERE code = 'AS')),
 ('Kyrgyzstan', 'KG', (SELECT id FROM continents WHERE code = 'AS')),
 ('Laos', 'LA', (SELECT id FROM continents WHERE code = 'AS')),
 ('Latvia', 'LV', (SELECT id FROM continents WHERE code = 'EU')),
 ('Lebanon', 'LB', (SELECT id FROM continents WHERE code = 'AS')),
 ('Lesotho', 'LS', (SELECT id FROM continents WHERE code = 'AF')),
 ('Liberia', 'LR', (SELECT id FROM continents WHERE code = 'AF')),
 ('Libya', 'LY', (SELECT id FROM continents WHERE code = 'AF')),
 ('Liechtenstein', 'LI', (SELECT id FROM continents WHERE code = 'EU')),
 ('Lithuania', 'LT', (SELECT id FROM continents WHERE code = 'EU')),
 ('Luxembourg', 'LU', (SELECT id FROM continents WHERE code = 'EU')),
 ('Macedonia', 'MK', (SELECT id FROM continents WHERE code = 'EU')),
 ('Madagascar', 'MG', (SELECT id FROM continents WHERE code = 'AF')),
 ('Malawi', 'MW', (SELECT id FROM continents WHERE code = 'AF')),
 ('Malaysia', 'MY', (SELECT id FROM continents WHERE code = 'AS')),
 ('Maldives', 'MV', (SELECT id FROM continents WHERE code = 'AS')),
 ('Mali', 'ML', (SELECT id FROM continents WHERE code = 'AF')),
 ('Malta', 'MT', (SELECT id FROM continents WHERE code = 'EU')),
 ('Man, Isle of', 'IM', (SELECT id FROM continents WHERE code = 'EU')),
 ('Marshall Islands', 'MH', (SELECT id FROM continents WHERE code = 'AU')),
 ('Martinique', 'MQ', (SELECT id FROM continents WHERE code = 'NA')),
 ('Mauritania', 'MR', (SELECT id FROM continents WHERE code = 'AF')),
 ('Mauritius', 'MU', (SELECT id FROM continents WHERE code = 'AF')),
 ('Mayotte', 'YT', (SELECT id FROM continents WHERE code = 'AF')),
 ('Mexico', 'MX', (SELECT id FROM continents WHERE code = 'NA')),
 ('Micronesia, Federated States of', 'FM', (SELECT id FROM continents WHERE code = 'AU')),
 ('Moldova', 'MD', (SELECT id FROM continents WHERE code = 'EU')),
 ('Monaco', 'MC', (SELECT id FROM continents WHERE code = 'EU')),
 ('Mongolia', 'MN', (SELECT id FROM continents WHERE code = 'AS')),
 ('Montenegro', 'ME', (SELECT id FROM continents WHERE code = 'EU')),
 ('Montserrat', 'MS', (SELECT id FROM continents WHERE code = 'NA')),
 ('Morocco', 'MA', (SELECT id FROM continents WHERE code = 'AF')),
 ('Mozambique', 'MZ', (SELECT id FROM continents WHERE code = 'AF')),
 ('Myanmar (Burma)', 'MM', (SELECT id FROM continents WHERE code = 'AS')),
 ('Namibia', 'NA', (SELECT id FROM continents WHERE code = 'AF')),
 ('Nauru', 'NR', (SELECT id FROM continents WHERE code = 'AU')),
 ('Nepal', 'NP', (SELECT id FROM continents WHERE code = 'AS')),
 ('Netherlands', 'NL', (SELECT id FROM continents WHERE code = 'EU')),
 ('Netherlands Antilles', 'AN', (SELECT id FROM continents WHERE code = 'NA')),
 ('New Caledonia', 'NC', (SELECT id FROM continents WHERE code = 'AU')),
 ('New Zealand', 'NZ', (SELECT id FROM continents WHERE code = 'AU')),
 ('Nicaragua', 'NI', (SELECT id FROM continents WHERE code = 'NA')),
 ('Niger', 'NE', (SELECT id FROM continents WHERE code = 'AF')),
 ('Nigeria', 'NG', (SELECT id FROM continents WHERE code = 'AF')),
 ('Niue', 'NU', (SELECT id FROM continents WHERE code = 'AU')),
 ('Norfolk Island', 'NF', (SELECT id FROM continents WHERE code = 'AU')),
 ('Northern Mariana Islands', 'MP', (SELECT id FROM continents WHERE code = 'AU')),
 ('Norway', 'NO', (SELECT id FROM continents WHERE code = 'EU')),
 ('Oman', 'OM', (SELECT id FROM continents WHERE code = 'AS')),
 ('Pakistan', 'PK', (SELECT id FROM continents WHERE code = 'AS')),
 ('Palau', 'PW', (SELECT id FROM continents WHERE code = 'AU')),
 ('Palestine', 'PS', (SELECT id FROM continents WHERE code = 'AS')),
 ('Panama', 'PA', (SELECT id FROM continents WHERE code = 'NA')),
 ('Papua New Guinea', 'PG', (SELECT id FROM continents WHERE code = 'AU')),
 ('Paraguay', 'PY', (SELECT id FROM continents WHERE code = 'SA')),
 ('Peru', 'PE', (SELECT id FROM continents WHERE code = 'SA')),
 ('Philippines', 'PH', (SELECT id FROM continents WHERE code = 'AS')),
 ('Pitcairn Islands', 'PN', (SELECT id FROM continents WHERE code = 'AU')),
 ('Poland', 'PL', (SELECT id FROM continents WHERE code = 'EU')),
 ('Portugal', 'PT', (SELECT id FROM continents WHERE code = 'EU')),
 ('Puerto Rico', 'PR', (SELECT id FROM continents WHERE code = 'NA')),
 ('Qatar', 'QA', (SELECT id FROM continents WHERE code = 'AS')),
 ('Reunion', 'RE', (SELECT id FROM continents WHERE code = 'AF')),
 ('Romania', 'RO', (SELECT id FROM continents WHERE code = 'EU')),
 ('Russia', 'RU', (SELECT id FROM continents WHERE code = 'AS')),
 ('Rwanda', 'RW', (SELECT id FROM continents WHERE code = 'AF')),
 ('Saint Kitts and Nevis', 'KN', (SELECT id FROM continents WHERE code = 'NA')),
 ('Saint Lucia', 'LC', (SELECT id FROM continents WHERE code = 'NA')),
 ('Saint Pierre and Miquelon', 'PM', (SELECT id FROM continents WHERE code = 'NA')),
 ('Saint Vincent and the Grenadines', 'VC', (SELECT id FROM continents WHERE code = 'NA')),
 ('San Marino', 'SM', (SELECT id FROM continents WHERE code = 'EU')),
 ('Sao Tome and Principe', 'ST', (SELECT id FROM continents WHERE code = 'AF')),
 ('Saudi Arabia', 'SA', (SELECT id FROM continents WHERE code = 'AS')),
 ('Senegal', 'SN', (SELECT id FROM continents WHERE code = 'AF')),
 ('Serbia', 'RS', (SELECT id FROM continents WHERE code = 'EU')),
 ('Seychelles', 'SC', (SELECT id FROM continents WHERE code = 'AF')),
 ('Sierra Leone', 'SL', (SELECT id FROM continents WHERE code = 'AF')),
 ('Singapore', 'SG', (SELECT id FROM continents WHERE code = 'AS')),
 ('Slovakia', 'SK', (SELECT id FROM continents WHERE code = 'EU')),
 ('Slovenia', 'SI', (SELECT id FROM continents WHERE code = 'EU')),
 ('Solomon Islands', 'SB', (SELECT id FROM continents WHERE code = 'AU')),
 ('Somalia', 'SO', (SELECT id FROM continents WHERE code = 'AF')),
 ('South Africa', 'ZA', (SELECT id FROM continents WHERE code = 'AF')),
 ('Spain', 'ES', (SELECT id FROM continents WHERE code = 'EU')),
 ('Sri Lanka', 'LK', (SELECT id FROM continents WHERE code = 'AS')),
 ('Sudan', 'SD', (SELECT id FROM continents WHERE code = 'AF')),
 ('Suriname', 'SR', (SELECT id FROM continents WHERE code = 'SA')),
 ('Svalbard', 'SJ', (SELECT id FROM continents WHERE code = 'EU')),
 ('Swaziland', 'SZ', (SELECT id FROM continents WHERE code = 'AF')),
 ('Sweden', 'SE', (SELECT id FROM continents WHERE code = 'EU')),
 ('Switzerland', 'CH', (SELECT id FROM continents WHERE code = 'EU')),
 ('Syria', 'SY', (SELECT id FROM continents WHERE code = 'AS')),
 ('Taiwan', 'TW', (SELECT id FROM continents WHERE code = 'AS')),
 ('Tajikistan', 'TJ', (SELECT id FROM continents WHERE code = 'AS')),
 ('Tanzania', 'TZ', (SELECT id FROM continents WHERE code = 'AF')),
 ('Thailand', 'TH', (SELECT id FROM continents WHERE code = 'AS')),
 ('Togo', 'TG', (SELECT id FROM continents WHERE code = 'AF')),
 ('Tokelau', 'TK', (SELECT id FROM continents WHERE code = 'AU')),
 ('Tonga', 'TO', (SELECT id FROM continents WHERE code = 'AU')),
 ('Trinidad and Tobago', 'TT', (SELECT id FROM continents WHERE code = 'NA')),
 ('Tunisia', 'TN', (SELECT id FROM continents WHERE code = 'AF')),
 ('Turkey', 'TR', (SELECT id FROM continents WHERE code = 'AS')),
 ('Turkmenistan', 'TM', (SELECT id FROM continents WHERE code = 'AS')),
 ('Turks and Caicos Islands', 'TC', (SELECT id FROM continents WHERE code = 'NA')),
 ('Tuvalu', 'TV', (SELECT id FROM continents WHERE code = 'AU')),
 ('Uganda', 'UG', (SELECT id FROM continents WHERE code = 'AF')),
 ('Ukraine', 'UA', (SELECT id FROM continents WHERE code = 'EU')),
 ('United Arab Emirates', 'AE', (SELECT id FROM continents WHERE code = 'AS')),
 ('United Kingdom', 'GB', (SELECT id FROM continents WHERE code = 'EU')),
 ('United States', 'US', (SELECT id FROM continents WHERE code = 'NA')),
 ('Uruguay', 'UY', (SELECT id FROM continents WHERE code = 'SA')),
 ('Uzbekistan', 'UZ', (SELECT id FROM continents WHERE code = 'AS')),
 ('Vanuatu', 'VU', (SELECT id FROM continents WHERE code = 'AU')),
 ('Venezuela', 'VE', (SELECT id FROM continents WHERE code = 'SA')),
 ('Vietnam', 'VN', (SELECT id FROM continents WHERE code = 'AS')),
 ('Virgin Islands', 'VI', (SELECT id FROM continents WHERE code = 'NA')),
 ('Wallis and Futuna', 'WF', (SELECT id FROM continents WHERE code = 'AU')),
 ('Western Sahara', 'EH', (SELECT id FROM continents WHERE code = 'AF')),
 ('Western Samoa', 'WS', (SELECT id FROM continents WHERE code = 'AU')),
 ('Yemen', 'YE', (SELECT id FROM continents WHERE code = 'AS')),
 ('Zaire (Dem Rep of Congo)', 'ZR', (SELECT id FROM continents WHERE code = 'AF')),
 ('Zambia', 'ZM', (SELECT id FROM continents WHERE code = 'AF')),
 ('Zimbabwe', 'ZW', (SELECT id FROM continents WHERE code = 'AF'))
;

INSERT INTO categories (name) VALUES ('Worth Seeing');
INSERT INTO categories (name) VALUES ('Accommodation');
INSERT INTO categories (name) VALUES ('Nightlife');
INSERT INTO categories (name) VALUES ('Shopping');
INSERT INTO categories (name) VALUES ('Culture & Art');
INSERT INTO categories (name) VALUES ('Transport');
INSERT INTO categories (name) VALUES ('Coffee & Drinks');
INSERT INTO categories (name) VALUES ('Food');
INSERT INTO categories (name) VALUES ('Activity');
INSERT INTO categories (name) VALUES ('Nature');
INSERT INTO categories (name) VALUES ('Entertainment');
INSERT INTO categories (name) VALUES ('Architecture');
INSERT INTO categories (name) VALUES ('Relax');
INSERT INTO categories (name) VALUES ('Other');